language: haskell

before_install:
    - export START=`pwd`
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install darcs libgmp3-dev libgmp3c2 freeglut3 freeglut3-dev
    - sudo apt-get build-dep ghc
    - sudo apt-get clean
    - cd
    - wget --prefer-family=IPv4 http://hdiff.luite.com/ghcjs/ghcjs-test.tar.xz
    - tar -xJf $HOME/ghcjs-test.tar.xz --strip-components=1
    - rm ghcjs-test.tar.xz
    - export PATH=$HOME/ghc/bin:$HOME/.cabal/bin:$HOME/jsshell:$HOME/node/bin:$PATH
    - cd $HOME/.cabal/bin
    - hash -r
    - cd $START

install:
    - pwd
    - export REPOSITORY_DIR=`pwd`
    - cd
    - git clone https://github.com/ghcjs/ghcjs
    - cd ghcjs
    - cabal install --enable-executable-dynamic --enable-tests
    - ghcjs-boot --reboot
    - cabal install --ghcjs stm random syb transformers text parallel QuickCheck old-time vector
    - cd $HOME/.ghcjs/x86*
    - ln -s $REPOSITORY_DIR shims
    - ghcjs-pkg list
    - cd
    - cd ghcjs

script:
    - ./dist/build/test/test -j 2 -t ghc -t conc -t integer -t ffi

env:
    - GHCJS_TEST_ONLYOPT=1
    - GHCJS_TEST_ONLYUNOPT=1

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true


