env:
    - GHCVER=7.8.3

before_install:
    - export GHCJS_BOOTING=1
    - export GHCJS_BOOTING_STAGE1=1
    - export SHIMS_REPO=`pwd`
    - git fetch --unshallow
    - sudo add-apt-repository -y ppa:hvr/ghc
    - sudo add-apt-repository -y ppa:chris-lea/node.js
    - sudo apt-get update -qq
    - sudo apt-get build-dep ghc
    - sudo apt-get install nodejs cabal-install-1.18 ghc-$GHCVER
    - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
    - cabal-1.18 update
    - cabal-1.18 install alex happy
    - mkdir _ghcjs_deps
    - cd _ghcjs_deps
    - git clone https://github.com/ghcjs/cabal.git
    - cd cabal
    - git checkout ghcjs
    - cabal-1.18 install ./Cabal ./cabal-install
    - cabal --version
    - cd ..
    - git clone https://github.com/ghcjs/ghcjs-prim.git
    - cd ghcjs-prim
    - git checkout $TRAVIS_BRANCH
    - cd ..
    - git clone https://github.com/ghcjs/haddock-internal.git
    - cd haddock-internal
    - git checkout $TRAVIS_BRANCH
    - cd ..
    - cabal install ./ghcjs-prim ./haddock-internal
    - git clone https://github.com/ghcjs/ghcjs.git
    - cd ghcjs
    - git checkout $TRAVIS_BRANCH
    - cd ..
    - cabal install ./ghcjs --enable-tests --enable-benchmarks
    - cd ..
    - ghcjs --version
    - ghcjs-boot --version
    - ghcjs-boot --dev --build-stage1-unbooted --with-node nodejs -j2 --no-prof --no-haddock --shims-dev-repo $SHIMS_REPO --shims-dev-branch $TRAVIS_COMMIT
    - cabal install -j2 --ghcjs random QuickCheck syb stm
    - ghcjs-pkg list
    - cd _ghcjs_deps/ghcjs

script:
    - ./dist/build/test/test --travis --with-node nodejs --no-profiling -j 2 -t ghc -t conc -t integer -t pkg

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true
